export const members = [
  { memberId: "2024-F0053", lastName: "SOIDIKI", firstName: "Djamila" },
  { memberId: "2024-F0054", lastName: "SOIDIKI", firstName: "Nasimata" },
  { memberId: "2024-F0059", lastName: "YOUNOUSSA", firstName: "Nadja" },
  { memberId: "2024-F0091", lastName: "SAMBEDJA", firstName: "Rahiya" },
  { memberId: "2024-F0099", lastName: "AHAMADA", firstName: "Yasmina" },
  { memberId: "2024-F0197", lastName: "MZE MCHINDA", firstName: "Nadjah" },
  { memberId: "2024-H0008", lastName: "BEN ABDOU", firstName: "Ali Mbae" },
  { memberId: "2024-H0026", lastName: "SAID", firstName: "Ahamada" },
  { memberId: "2024-H0043", lastName: "BOINA", firstName: "Azume" },
  { memberId: "2024-H0044", lastName: "BOINA", firstName: "Azal" },
  { memberId: "2024-H0048", lastName: "BOONE", firstName: "Jeremy" },
  { memberId: "2024-H0054", lastName: "SAANDI ALI", firstName: "Djamal" },
  { memberId: "2024-H0055", lastName: "MZEMBABA", firstName: "Ismael" },
  { memberId: "2024-H0075", lastName: "ABDOUL-WAHIDI", firstName: "Mohamed" },
  { memberId: "2024-H0076", lastName: "MOHAMED", firstName: "Adrami" },
  { memberId: "2024-H0083", lastName: "MOHAMED", firstName: "Said" },
  { memberId: "2024-H0091", lastName: "MMADI YOUSSOUF", firstName: "Hassani" },
  { memberId: "2024-H0119", lastName: "ALI", firstName: "Hachim" },
  { memberId: "2024-H0150", lastName: "ISSOUF", firstName: "Mounir" },
  { memberId: "2024-W0037", lastName: "BOINA", firstName: "Kamal" },
  { memberId: "2024-W0046", lastName: "ABDOU", firstName: "Mmadi" },
  { memberId: "2024-W0057", lastName: "MBAE", firstName: "Kassim" },
  { memberId: "2024-W0058", lastName: "BOINA", firstName: "Halidi" },
  { memberId: "2024-W0060", lastName: "ALI MLADJAO", firstName: "Said" },
  { memberId: "2024-W0064", lastName: "MZEMBABA BOINA", firstName: "Ali" },
  { memberId: "2024-F0003", lastName: "SAMBEDJA", firstName: "Fatima" },
  { memberId: "2024-F0091", lastName: "SAMBEDJA", firstName: "Rahia" },
  { memberId: "W0050", lastName: "SAMBEDJA", firstName: "Ali" },
  { memberId: "2024-H0046", lastName: "M'MADI", firstName: "Ali" },
  { memberId: "2024-H0160", lastName: "MOUMINI", firstName: "Ibrahim" },
  { memberId: "2024-H0159", lastName: "HAMIDOU", firstName: "Ismaila" },
  { memberId: "F0098", lastName: "DAROUCHE", firstName: "Sarah" },
  { memberId: "2024-H0118", lastName: "ALI", firstName: "Hassane" },
  { memberId: "W0060", lastName: "ALI MLADJAO", firstName: "Said" },
  { memberId: "2024-H0071", lastName: "NOUHOU", firstName: "Mohamed" },
  { memberId: "2024-H0001", lastName: "ABAL", firstName: "Hamza" },
  { memberId: "2024-H0047", lastName: "BOINA", firstName: "Mohamed" },
  { memberId: "2024-H0060", lastName: "DAROUCHE", firstName: "Wadjib" },
  { memberId: "2024-H0092", lastName: "MZE", firstName: "Said" },
  { memberId: "2024-H0111", lastName: "MOHAMED", firstName: "Moussa" },
  { memberId: "2024-H0117", lastName: "SAADI", firstName: "Mahamoudou" },
  { memberId: "2024-H0131", lastName: "SAID", firstName: "Ahamada" },
  { memberId: "2024-H0161", lastName: "MNEMOI", firstName: "Dany" },
  { memberId: "2024-H0162", lastName: "MZE", firstName: "Elias" },
  { memberId: "W0067", lastName: "OMAR", firstName: "Ali" },
  { memberId: "2024-H0089", lastName: "M'HOUDINI", firstName: "Abdelazdy" },
  { memberId: "2024-H0130", lastName: "MHADJOU", firstName: "Soifoine" },
  { memberId: "W0043", lastName: "SAID", firstName: "Farid" },
  { memberId: "W0074", lastName: "HAMIDOU", firstName: "Ali" },
  { memberId: "W0033", lastName: "BOINA", firstName: "Taky" },
  { memberId: "W0061", lastName: "MZEMBABA", firstName: "Ben Said" },
  { memberId: "W0054", lastName: "MAHAMOUD", firstName: "Nacer" },
  { memberId: "2024-H0112", lastName: "MZÉ", firstName: "Mohamed" },
  { memberId: "2024-H0163", lastName: "ZILÉ", firstName: "Fahar" },
  { memberId: "2024-H0164", lastName: "MHOUMADI", firstName: "Kamal" },
  { memberId: "2024-H0104", lastName: "MOHAMED", firstName: "Djamal" },
  { memberId: "W0056", lastName: "MZÉ MOUIGNI", firstName: "Kamal" },
  { memberId: "2024-H0069", lastName: "HATUBOU", firstName: "Benali" },
  { memberId: "2024-H0133", lastName: "SAMBEDJA", firstName: "Hicham" },
  { memberId: "W0071", lastName: "TOYB", firstName: "Halidi" },
  { memberId: "F0179", lastName: "HAMIDOU", firstName: "Naïma" },
  { memberId: "F0180", lastName: "SAID", firstName: "Djamila" },
  { memberId: "F0049", lastName: "AHAMADA", firstName: "Fatouma" },
  { memberId: "2024-H0028", lastName: "MOHAMED", firstName: "Djoumoi" },
  { memberId: "2024-H0147", lastName: "YOUNOUSSA", firstName: "Salim" },
  { memberId: "2024-H0080", lastName: "HAMIDOU", firstName: "Mamoune" },
  { memberId: "2024-H0081", lastName: "HAMIDOU", firstName: "Maamir" },
  { memberId: "2024-H0172", lastName: "MHOUMADI", firstName: "Karim" },
  { memberId: "W0038", lastName: "MOUMINI", firstName: "Said" },
  { memberId: "F0036", lastName: "MOHAMED", firstName: "Zaïdati" },
  { memberId: "2024-H0026", lastName: "MOUMINI", firstName: "Saïd" },
  { memberId: "2024-H0173", lastName: "YOUSSOUF IBRAHIM", firstName: "Ali" },
  { memberId: "2024-H0077", lastName: "MOHAMED", firstName: "Victor" },
  { memberId: "F0157", lastName: "MMADI", firstName: "Touma" },
  { memberId: "F0088", lastName: "ISSOUF", firstName: "Nassuria" },
  { memberId: "W0027", lastName: "SAÏD ALI", firstName: "Soilihi" },
  { memberId: "F0169", lastName: "BOURHANI", firstName: "Nadjati" },
  { memberId: "F0209", lastName: "MMADI", firstName: "Hadidja" },
  { memberId: "2024-H0158", lastName: "IBRAHIM", firstName: "Youssouf" },
  { memberId: "2024-H0131", lastName: "SAID", firstName: "Ahamada" },
  { memberId: "W0019", lastName: "ABDOU", firstName: "Ali Saïd Djaïz" },
  { memberId: "2024-H0174", lastName: "MBAÉ", firstName: "Said Ali" },
  { memberId: "2024-H0027", lastName: "SAÏD", firstName: "Azedine" },
  { memberId: "2024-H0145", lastName: "YOUNOUSSA", firstName: "Hadji" },
  { memberId: "2024-H0100", lastName: "ALI", firstName: "Djamaldine" },
  { memberId: "2024-H0123", lastName: "SAID", firstName: "Maoulana" },
  { memberId: "2024-H0064", lastName: "SAID", firstName: "Andhum" },
  { memberId: "F0213", lastName: "ALI", firstName: "Koudeidi" },
  { memberId: "2024-H0066", lastName: "HAKIM", firstName: "Ahmed" },
  { memberId: "2024-H0142", lastName: "SAID", firstName: "Abdallah" },
  { memberId: "F0080", lastName: "AHAMADA", firstName: "Toilanti" },
  { memberId: "2024-H0074", lastName: "MOHAMED", firstName: "Taoufiki" },
  { memberId: "W0047", lastName: "MOHAMED", firstName: "Ali" },
  { memberId: "2024-H0062", lastName: "ASSOUMANI", firstName: "Hadji" },
  { memberId: "2024-H0110", lastName: "ABDOU", firstName: "Moussa Ibrahim" },
  { memberId: "2024-H0065", lastName: "HAKIM", firstName: "Mohamed" },
  { memberId: "2024-H0178", lastName: "YOUSSOUF", firstName: "Mohamed" },
  { memberId: "2024-H0122", lastName: "SAID", firstName: "Hassani" },
  { memberId: "2024-H0093", lastName: "MOGNI", firstName: "Beni" },
  { memberId: "2024-H0127", lastName: "SAID ADAM", firstName: "Ahmed" },
  { memberId: "2024-H0178", lastName: "YOUSSOUF", firstName: "Mohamed" },
];
